package Hibernate;
// Generated 18-Jun-2015 13:49:14 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Student generated by hbm2java
 */
@Entity
@Table(name="student"
    ,catalog="practicesql"
)
public class Student  implements java.io.Serializable {


     private int studentId;
     private Classes classes;
     private String firstName;
     private String lastName;
     private Date dob;
     private int year;

    public Student() {
    }

    public Student(int studentId, Classes classes, String firstName, String lastName, Date dob, int year) {
       this.studentId = studentId;
       this.classes = classes;
       this.firstName = firstName;
       this.lastName = lastName;
       this.dob = dob;
       this.year = year;
    }
   
     @Id 

    
    @Column(name="StudentID", unique=true, nullable=false)
    public int getStudentId() {
        return this.studentId;
    }
    
    public void setStudentId(int studentId) {
        this.studentId = studentId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ClassEnrolled", nullable=false)
    public Classes getClasses() {
        return this.classes;
    }
    
    public void setClasses(Classes classes) {
        this.classes = classes;
    }

    
    @Column(name="FirstName", nullable=false, length=250)
    public String getFirstName() {
        return this.firstName;
    }
    
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    
    @Column(name="LastName", nullable=false, length=250)
    public String getLastName() {
        return this.lastName;
    }
    
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DOB", nullable=false, length=10)
    public Date getDob() {
        return this.dob;
    }
    
    public void setDob(Date dob) {
        this.dob = dob;
    }

    
    @Column(name="Year", nullable=false)
    public int getYear() {
        return this.year;
    }
    
    public void setYear(int year) {
        this.year = year;
    }




}


