package Hibernate;
// Generated Sep 4, 2015 6:55:56 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Teacher generated by hbm2java
 */
@Entity
@Table(name="teacher"
    ,catalog="practicesql"
)
public class Teacher  implements java.io.Serializable {


     private Integer teacherId;
     private Date recordDate;
     private String firstName;
     private String lastName;
     private String specialSubject;
     private Set<Teacherclasses> teacherclasseses = new HashSet<Teacherclasses>(0);

    public Teacher() {
    }

	
    public Teacher(Date recordDate, String firstName, String lastName, String specialSubject) {
        this.recordDate = recordDate;
        this.firstName = firstName;
        this.lastName = lastName;
        this.specialSubject = specialSubject;
    }
    public Teacher(Date recordDate, String firstName, String lastName, String specialSubject, Set<Teacherclasses> teacherclasseses) {
       this.recordDate = recordDate;
       this.firstName = firstName;
       this.lastName = lastName;
       this.specialSubject = specialSubject;
       this.teacherclasseses = teacherclasseses;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="TeacherID", unique=true, nullable=false)
    public Integer getTeacherId() {
        return this.teacherId;
    }
    
    public void setTeacherId(Integer teacherId) {
        this.teacherId = teacherId;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="RecordDate", nullable=false, length=10)
    public Date getRecordDate() {
        return this.recordDate;
    }
    
    public void setRecordDate(Date recordDate) {
        this.recordDate = recordDate;
    }

    
    @Column(name="FirstName", nullable=false, length=250)
    public String getFirstName() {
        return this.firstName;
    }
    
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    
    @Column(name="LastName", nullable=false, length=250)
    public String getLastName() {
        return this.lastName;
    }
    
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    
    @Column(name="SpecialSubject", nullable=false, length=250)
    public String getSpecialSubject() {
        return this.specialSubject;
    }
    
    public void setSpecialSubject(String specialSubject) {
        this.specialSubject = specialSubject;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="teacher")
    public Set<Teacherclasses> getTeacherclasseses() {
        return this.teacherclasseses;
    }
    
    public void setTeacherclasseses(Set<Teacherclasses> teacherclasseses) {
        this.teacherclasseses = teacherclasseses;
    }




}


