package Hibernate;
// Generated 18-Jun-2015 13:49:14 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Teacher generated by hbm2java
 */
@Entity
@Table(name="teacher"
    ,catalog="practicesql"
)
public class Teacher  implements java.io.Serializable {


     private int teacherId;
     private Date recordDate;
     private String firstName;
     private String lastName;
     private String specialSubject;
     private Set<Classes> classeses = new HashSet<Classes>(0);

    public Teacher() {
    }

	
    public Teacher(int teacherId, Date recordDate, String firstName, String lastName, String specialSubject) {
        this.teacherId = teacherId;
        this.recordDate = recordDate;
        this.firstName = firstName;
        this.lastName = lastName;
        this.specialSubject = specialSubject;
    }
    public Teacher(int teacherId, Date recordDate, String firstName, String lastName, String specialSubject, Set<Classes> classeses) {
       this.teacherId = teacherId;
       this.recordDate = recordDate;
       this.firstName = firstName;
       this.lastName = lastName;
       this.specialSubject = specialSubject;
       this.classeses = classeses;
    }
   
     @Id 

    
    @Column(name="TeacherID", unique=true, nullable=false)
    public int getTeacherId() {
        return this.teacherId;
    }
    
    public void setTeacherId(int teacherId) {
        this.teacherId = teacherId;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="RecordDate", nullable=false, length=10)
    public Date getRecordDate() {
        return this.recordDate;
    }
    
    public void setRecordDate(Date recordDate) {
        this.recordDate = recordDate;
    }

    
    @Column(name="FirstName", nullable=false, length=250)
    public String getFirstName() {
        return this.firstName;
    }
    
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    
    @Column(name="LastName", nullable=false, length=250)
    public String getLastName() {
        return this.lastName;
    }
    
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    
    @Column(name="SpecialSubject", nullable=false, length=250)
    public String getSpecialSubject() {
        return this.specialSubject;
    }
    
    public void setSpecialSubject(String specialSubject) {
        this.specialSubject = specialSubject;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="teacher")
    public Set<Classes> getClasseses() {
        return this.classeses;
    }
    
    public void setClasseses(Set<Classes> classeses) {
        this.classeses = classeses;
    }




}


