package Hibernate;
// Generated 13-Aug-2015 09:53:13 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Users generated by hbm2java
 */
@Entity
@Table(name="users"
    ,catalog="practicesql"
    , uniqueConstraints = @UniqueConstraint(columnNames="userName") 
)
public class Users  implements java.io.Serializable {


     private Integer id;
     private String userName;
     private String userPassword;
     private boolean administer;
     private String studentId;
     private String teacherId;
     private Date lastLogin;
     private String sessionId;

    public Users() {
    }

	
    public Users(String userPassword, boolean administer) {
        this.userPassword = userPassword;
        this.administer = administer;
    }
    public Users(String userName, String userPassword, boolean administer, String studentId, String teacherId, Date lastLogin, String sessionId) {
       this.userName = userName;
       this.userPassword = userPassword;
       this.administer = administer;
       this.studentId = studentId;
       this.teacherId = teacherId;
       this.lastLogin = lastLogin;
       this.sessionId = sessionId;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="userName", unique=true, length=252)
    public String getUserName() {
        return this.userName;
    }
    
    public void setUserName(String userName) {
        this.userName = userName;
    }

    
    @Column(name="UserPassword", nullable=false, length=251)
    public String getUserPassword() {
        return this.userPassword;
    }
    
    public void setUserPassword(String userPassword) {
        this.userPassword = userPassword;
    }

    
    @Column(name="Administer", nullable=false)
    public boolean isAdminister() {
        return this.administer;
    }
    
    public void setAdminister(boolean administer) {
        this.administer = administer;
    }

    
    @Column(name="StudentId", length=251)
    public String getStudentId() {
        return this.studentId;
    }
    
    public void setStudentId(String studentId) {
        this.studentId = studentId;
    }

    
    @Column(name="TeacherId", length=251)
    public String getTeacherId() {
        return this.teacherId;
    }
    
    public void setTeacherId(String teacherId) {
        this.teacherId = teacherId;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="LastLogin", length=10)
    public Date getLastLogin() {
        return this.lastLogin;
    }
    
    public void setLastLogin(Date lastLogin) {
        this.lastLogin = lastLogin;
    }

    
    @Column(name="SessionID", length=251)
    public String getSessionId() {
        return this.sessionId;
    }
    
    public void setSessionId(String sessionId) {
        this.sessionId = sessionId;
    }




}


