package Hibernate;
// Generated 26-Jun-2015 08:25:17 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Visitors generated by hbm2java
 */
@Entity
@Table(name="visitors"
    ,catalog="practicesql"
)
public class Visitors  implements java.io.Serializable {


     private Integer id;
     private String ipAddress;

    public Visitors() {
    }

    public Visitors(String ipAddress) {
       this.ipAddress = ipAddress;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="ipAddress", nullable=false)
    public String getIpAddress() {
        return this.ipAddress;
    }
    
    public void setIpAddress(String ipAddress) {
        this.ipAddress = ipAddress;
    }




}


