package Hibernate;
// Generated Sep 4, 2015 6:55:56 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Visitors generated by hbm2java
 */
@Entity
@Table(name="visitors"
    ,catalog="practicesql"
)
public class Visitors  implements java.io.Serializable {


     private Integer id;
     private String ipAddress;
     private String passwordSubmitted;
     private String loginName;
     private Date lastRequested;

    public Visitors() {
    }

	
    public Visitors(String ipAddress) {
        this.ipAddress = ipAddress;
    }
    public Visitors(String ipAddress, String passwordSubmitted, String loginName, Date lastRequested) {
       this.ipAddress = ipAddress;
       this.passwordSubmitted = passwordSubmitted;
       this.loginName = loginName;
       this.lastRequested = lastRequested;
    }
    
    public Visitors(String ipAddress, String passwordSubmitted, String loginName) {
       this.ipAddress = ipAddress;
       this.passwordSubmitted = passwordSubmitted;
       this.loginName = loginName;
       this.lastRequested = new Date();
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="ipAddress", nullable=false)
    public String getIpAddress() {
        return this.ipAddress;
    }
    
    public void setIpAddress(String ipAddress) {
        this.ipAddress = ipAddress;
    }

    
    @Column(name="PasswordSubmitted", length=251)
    public String getPasswordSubmitted() {
        return this.passwordSubmitted;
    }
    
    public void setPasswordSubmitted(String passwordSubmitted) {
        this.passwordSubmitted = passwordSubmitted;
    }

    
    @Column(name="LoginName", length=251)
    public String getLoginName() {
        return this.loginName;
    }
    
    public void setLoginName(String loginName) {
        this.loginName = loginName;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="LastRequested", length=10)
    public Date getLastRequested() {
        return this.lastRequested;
    }
    
    public void setLastRequested(Date lastRequested) {
        this.lastRequested = lastRequested;
    }




}


